#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm -O HDMI-0 DVI-I-0
bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DVI-I-0 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          20
bspc config split_ratio          0.50

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#1d2021"
bspc config focused_border_color "#504946"

bspc rule -a google-chrome desktop=1 follow=off
bspc rule -a code-oss desktop=2 follow=off
bspc rule -a discord desktop=6 follow=off
bspc rule -a spotify desktop=7 follow=off

# Polybar
sh $HOME/.config/polybar/launch.sh &

# Background
feh --bg-fill --no-xinerama $HOME/Pictures/Wallpaper/wp.png
